![video_game](video_game.jpg)

Video games are big business: the global gaming market is projected to be worth more than $300 billion by 2027 according to Mordor Intelligence. With so much money at stake, the major game publishers are hugely incentivized to create the next big hit. But are games getting better, or has the golden age of video games already passed?

In this project, you'll analyze video game critic and user scores as well as sales data for the top 400 video games released since 1977. You'll search for a golden age of video games by identifying release years that users and critics liked best, and you'll explore the business side of gaming by looking at game sales data.

Your search will involve joining datasets and comparing results with set theory. You'll also filter, group, and order data. Make sure you brush up on these skills before trying this project! The database contains two tables. Each table has been limited to 400 rows for this project, but you can find the complete dataset with over 13,000 games on Kaggle.

### `game_sales` table

| Column | Definition | Data Type |
|-|-|-|  
|name|Name of the video game|`varchar`|
|platform|Gaming platform|`varchar`|
|publisher|Game publisher|`varchar`|
|developer|Game developer|`varchar`|
|games_sold|Number of copies sold (millions)|`float`|
|year|Release year|`int`|

### `reviews` table

| Column | Definition | Data Type |
|-|-|-|
|name|Name of the video game|`varchar`|  
|critic_score|Critic score according to Metacritic|`float`|
|user_score|User score according to Metacritic|`float`|


### `users_avg_year_rating` table

| Column | Definition | Data Type |
|-|-|-|
|year| Release year of the games reviewed |`int`|  
|num_games| Number of games released that year |`int`|
|avg_user_score| Average score of all the games ratings for the year |`float`|

### `critics_avg_year_rating` table

| Column | Definition | Data Type |
|-|-|-|
|year| Release year of the games reviewed |`int`|  
|num_games| Number of games released that year |`int`|
|avg_critic_score| Average score of all the games ratings for the year |`float`|

## 1. Best-Selling Games
Description: This query identifies the top 10 best-selling games by sorting the game_sales table in descending order based on the games_sold column. It ensures that we capture the most commercially successful games in the dataset.

Key Points:
- Used ORDER BY games_sold DESC to prioritize games with the highest sales.
- Limited the result to 10 rows with LIMIT 10.

In [19]:
-- best_selling_games
SELECT *
FROM game_sales
ORDER BY games_sold DESC
LIMIT 10;

                                        name platform  ... games_sold  year
0                         Wii Sports for Wii      Wii  ...      82.90  2006
1                  Super Mario Bros. for NES      NES  ...      40.24  1985
2    Counter-Strike: Global Offensive for PC       PC  ...      40.00  2012
3                     Mario Kart Wii for Wii      Wii  ...      37.32  2008
4       PLAYERUNKNOWN'S BATTLEGROUNDS for PC       PC  ...      36.60  2017
5                           Minecraft for PC       PC  ...      33.15  2010
6                  Wii Sports Resort for Wii      Wii  ...      33.13  2009
7  Pokemon Red / Green / Blue Version for GB       GB  ...      31.38  1998
8               New Super Mario Bros. for DS       DS  ...      30.80  2006
9          New Super Mario Bros. Wii for Wii      Wii  ...      30.30  2009

[10 rows x 6 columns]

## 2. Top Years by Critic Scores
The query finds the 10 years with the highest average critic scores, including only years where at least 4 games were released. The average critic score is rounded to 2 decimal places for clarity.

Key Points:

- Included a filter with WHERE num_games >= 4 to ensure a significant sample size.
- Used ROUND(avg_critic_score, 2) for better presentation.
- Results are ordered by the critic score in descending order to highlight the top years.

In [20]:
-- critics_top_ten_years
SELECT year,
		num_games,
		ROUND(avg_critic_score, 2) AS avg_critic_score
FROM critics_avg_year_rating
WHERE num_games >= 4
ORDER BY avg_critic_score DESC
LIMIT 10;

   year  num_games  avg_critic_score
0  1998         10              9.32
1  2004         11              9.03
2  2002          9              8.99
3  1999         11              8.93
4  2001         13              8.82
5  2011         26              8.76
6  2016         13              8.67
7  2013         18              8.66
8  2008         20              8.63
9  2017         13              8.62

## Query 3: Golden Years
This query identifies years where critics and users highly rated the games released. It combines data from users_avg_year_rating and critics_avg_year_rating, filtering for years where either the average user score or critic score was greater than 9.

Key Points:
- Performed a JOIN between the users_avg_year_rating and critics_avg_year_rating tables based on the year column.
- Added a calculated column, diff, showing the difference between the average critic and user scores.
- Results are ordered by year in ascending order for chronological analysis.

In [21]:
-- golden_years
SELECT users_avg_year_rating.year, users_avg_year_rating.num_games, users_avg_year_rating.avg_user_score, critics_avg_year_rating.avg_critic_score, (critics_avg_year_rating.avg_critic_score - users_avg_year_rating.avg_user_score) AS diff
FROM users_avg_year_rating
JOIN critics_avg_year_rating
ON users_avg_year_rating.year = critics_avg_year_rating.year
WHERE users_avg_year_rating.avg_user_score > 9
OR critics_avg_year_rating.avg_critic_score > 9
ORDER BY users_avg_year_rating.year ASC;

   year  num_games  avg_user_score  avg_critic_score  diff
0  1997          8            9.50              7.93 -1.57
1  1998         10            9.40              9.32 -0.08
2  2004         11            8.55              9.03  0.48
3  2008         20            9.03              8.63 -0.40
4  2009         20            9.18              8.55 -0.63
5  2010         23            9.24              8.41 -0.83